<?php
header("Content-Type: text/html; charset=utf-8");
if ($this->url) {
	$log = "<center><a href='authentication/logout'>logout</a></center></div>";
	$adminpanel = "<li><a href='Adminpanel'>Админ панель</a></li>";
}
else {
	$log = "<center><a href='authentication/login'>login</a></center></div>";
}
echo "<div class='cent'>";
$text = wordwrap($this->content[0]["page_text"], 100, "<br />\n");
echo $text;
echo "</div>";

?>

